---
# tasks file for slavejenkins

- name: Put SELINUX in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Disable SELINUX
  selinux:
    state: disabled

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Install EPEL Repository
  yum: pkg=epel-release state=latest

- name: Upgrade System Packages
  yum: name=* state=latest

- name: Install Java 7/8
  yum: pkg={{item}}
  with_items:
      - java-1.7.0-openjdk
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - java-1.7.0-openjdk-devel

- name: Install Required Packages
  yum: pkg={{ item }} state=installed
  with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python-pip
      - htop
      - vim
      - git
      - curl
      - wget
      - openssl-devel
      - freetds
      - freetds-devel
      - zenity

- name: Install Development Tools
  yum:
    name: "@Development tools"
    state: present
  become: yes

- name: Upgrade Python-pip
  shell: pip install --upgrade pip


- name: Get Docker package
  get_url: 
      url: https://get.docker.com
      dest: /tmp/docker-install.sh
      mode: 0777

- name: Exec Docker Install Script
  shell: /tmp/docker-install.sh

- name: Start Docker Service
  service:
     name: docker
     state: started

- name: Enable Docker Service
  service:
     name: docker
     enabled: yes  

- name: Install docker-compose
  shell: pip install docker-compose

- name: Install awscli
  shell: pip install awscli

- name: Create jenkins user
  user:
    name: '{{ jenkins_username }}'
    home: '{{ jenkins_home }}'
    shell: /bin/bash
    state: present

- name: Promote jenkins user sudoer
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ jenkins_username }}    ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Download nodejs repository
  shell: curl -sL https://rpm.nodesource.com/setup_6.x | bash

- name: Install nodejs@6.11.0
  yum:
    name: nodejs-6.11.0
    state: present

- import_tasks: install-maven.yml

- name: Create cronjob task to delete workspace
  cron:
     name: Delete jenkins workspace
     weekday: "*"
     minute: "00"
     hour: "23"
     user: "root"
     job: "rm -rf /var/lib/jenkins_slave/workspace/* > /dev/null"


- import_tasks: install-npm-packages.yml

- name: Create .m2 directory
  file:
     path: ~/.m2
     state: directory
     owner: root
     group: root
     mode: 0755

- name: Create aws directory
  file:
     path: ~/.aws
     state: directory
     owner: root
     group: root
     mode: 0755

- name: Copy m2 settings
  copy:
     src: settings.xml
     dest: /root/.m2/settings.xml
     owner: root
     group: root
     mode: 0755

- import_tasks: install-ruby.yml

- import_tasks: install-gems.yml

- name: Download sdk folder
  get_url:
     url: https://bit.ly/2IG1nzG    
     dest: /opt/
     mode: 0755

- name: Extract sdk folder
  shell: tar -xvf /opt/sdk.tar.gz -C /opt

- name: Download Gradle
  get_url:
     url: https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
     dest: /opt
     mode: 0755

- name: Extract gradle package
  shell: yes | unzip /opt/gradle-4.10.2-bin.zip -d /opt
    

- name: Copy database.yml
  copy:
     src: database.yml
     dest: /var/lib/jenkins_slave/database.yml
     owner: root
     group: root
     mode: 0755

- name: Copy AWS credentials
  copy:
    src: credentials
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: 0750

- name: Copy AWS config
  copy:
    src: config
    dest: /root/.aws/config
    owner: root
    group: root
    mode: 0750
